version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: chat_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432" # Expose on port 5433
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: chat_app_redis
    ports:
      - "6379:6379" # Expose on port 6379

volumes:
  db_data:
